config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get "/profile", to: "users#profile", as: "profile"
  get "mentorships", to: "mentorships#index"
  get "my_proposals", to: "mentorships#my_proposals"

  resources :users do
    resources :mentorships, only: :create
  end
  resources :mentorships, only: [:update, :destroy]
  resources :skills
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :student, class_name: 'User'
  belongs_to :mentor, class_name: 'User'
end

app/models/mentorship.rb
class Mentorship < ApplicationRecord
  belongs_to :student, class_name: 'User'
  belongs_to :mentor, class_name: 'User'
  has_one_attached :photo


  validates :student, uniqueness: { scope: :mentor, message: "Solicitação já enviada" }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  LANGUAGES = ["JavaScript",
    "Ruby",
    "Python",
    "Java",
    "PHP",
    "C#",
    "C++",
    "TypeScript",
    "C",
    "Swift",
    "R",
    "Objective-C",
    "Scala",
    "Shell",
    "Go",
    "PowerShell",
    "Kotlin",
    "Rust",
    "Dart",
    "CSS"]
    validates :language, uniqueness: {scope: :user}
    validate :less_than_three

  def less_than_three
    if Skill.where(user: user).count >= 3
      errors.add(:language, "Maximo tres linguagens")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :student_mentorships, class_name: 'Mentorships', foreign_key: 'student_id'
  has_many :mentor_mentorships, class_name: 'Mentorships', foreign_key: 'mentor_id'
  has_many :skills, dependent: :destroy
  has_one_attached :photo
  validates :description, length: { maximum: 300 }
  validates :username, length: { maximum: 16 }
  validates :student, inclusion: [true, false]
  validates :username, presence: true, uniqueness: true
  include PgSearch::Model

  pg_search_scope :search_by_name_and_language,
  against: [ :username, :first_name, :last_name],
   associated_against:
    { skills: [ :language ] },
    using: {
      tsearch: { prefix: true }
    }

  accepts_nested_attributes_for :skills, update_only: true


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def mentor?
    student == false
  end

  def student?
    student
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:student, :username, :photo, :description])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo, :description, :skills, skills_attributes: [:language, :id]])
  end

  def after_sign_in_path_for(resource)
    profile_path
  end

  def after_sign_up_path_for(resource)
    profile_path
 end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

 # def create
 #   @chatroom = Chatroom.create!(params)
 # end

  def show
    @chatroom = Chatroom.find(params[:id])
    # achar a mentoria exata do usuario e o mentor
    @message = Message.new
  end
end

app/controllers/mentorships_controller.rb
class MentorshipsController < ApplicationController
  before_action :set_mentorship, only: [:update, :destroy]

 def index
    if params[:query].present?
      @mentors = User.search_by_name_and_language(params[:query])
    else
      @mentors = User.where(student: false)
    end
  end

  def new
  end

  def create
    @mentorship = Mentorship.new
    @mentor = User.find(params[:user_id])
    @student = current_user
    @mentorship.mentor_id = @mentor.id
    @mentorship.student_id = @student.id
    if @mentorship.save
      redirect_to my_proposals_path
    else
      redirect_to profile_path, alert: "Solicitação já enviada"
    end
  end

  def my_proposals
    if current_user.student
      @mentorships = Mentorship.where(student: current_user)
    else
      @mentorships = Mentorship.where(mentor: current_user)
    end
  end

  def update
    # essa rota vai trocar o valor do boolean accepted -> responsabilidade do mentor
    @mentorship.update(accepted: :true)
    # tem que ter um chatroom.create find or create_by
    mentor = @mentorship.mentor
    student = @mentorship.student
    name = "#{mentor.username} x #{student.username}"
    @chatroom = Chatroom.find_or_create_by!(student: student, mentor: mentor, name: name)
    # e redirecionar pro chatroom
    redirect_to chatroom_path(@chatroom)
  end

  def destroy
    mentor = @mentorship.mentor
    student = @mentorship.student
    name = "#{mentor.username} x #{student.username}"
    @chatroom = Chatroom.find_or_create_by!(student: student, mentor: mentor, name: name)
    @chatroom.destroy
    @mentorship.destroy
    redirect_to my_proposals_path
  end

  private

  def set_mentorship
    @mentorship = Mentorship.find(params[:id])
  end


  def mentorship_params
    params.require(:mentorship).permit(:accepted, :completed, :photo)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      # redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      head :ok
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.user = current_user
    if @skill.save
      redirect_to profile_path, notice: "#{@skill.language} added with success!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    if @skill.destroy
      flash[:notice] = "#{@skill.language} removed"
      redirect_to profile_path
    end
  end

  private

  def skill_params
    params.require(:skill).permit(:language)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<div class="container chatroom" data-controller="chatroom-subscription" data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
  <h1><%= @chatroom.name %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render 'messages/message', message: message  %>
    <% end %>
  </div>

<!-- se a mentorship(ter no controler de show) do current user estiver com o completed -> true não manda mais mensagem -->

<%= simple_form_for [@chatroom, @message], remote: true, html: {class: "d-flex", data: { chatroom_subscription_target: 'form', action: "turbo:submit-end->chatroom-subscription#resetForm" } } do |f| %>
  <%= f.input :content,
    label: false,
    placeholder: "Message ##{@chatroom.name}",
    wrapper_html: {class: "flex-grow-1"}
  %>
  
  <%= f.submit "Enviar", class: "btn btn-default-update" %>
<% end %>
</div>

<div class="d-flex justify-content-center"><%= link_to "Voltar", profile_path, class: "btn-default" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>girls.match</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Annie+Use+Your+Telescope&family=Press+Start+2P&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mynerve&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mynerve&family=Work+Sans:wght@300;400&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
  <div class="mb-75">
    <%= yield %>
  </div>

  <%= render "shared/footer" %>
  </body>
</html>

app/views/mentorships/index.html.erb
<div class="container">
  <%= form_with url: mentorships_path, method: :get, class:"align-form-center" do %>
    <%= text_field_tag :query,
      params[:query],
      placeholder: "Buscar por linguagem"
    %>
    <%= submit_tag "🔎", class: "s-style-buttom" %>
  <% end %>

  <div class="row jc-center">
    <% @mentors.each do |mentor| %>
      <div class="card-mentors col-4 d-flex flex-column">
        <p><%= mentor.username.capitalize  %></p>
        <% image_url =  mentor.photo.attached? ? cl_image_path(mentor.photo.key) : "https://www.promoview.com.br/uploads/images/unnamed%2819%29.png" %>
        <div class="user-img" style="background-image: url('<%= image_url %>');">
        </div>
          <% if mentor.available %>
            <%= link_to "Ver perfil!", user_path(mentor), class: "btn-default-big mx-auto" %>
          <% else %>
            <p>Mentora não disponível</p>
          <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to "Voltar", profile_path, class: "btn-default btn-skills" %>
</div>

app/views/mentorships/my_proposals.html.erb
<div class="container">
  <h1 class="sign"> Seus convites </h1>


  <div class="row">
    <% @mentorships.each do |mentorship| %>
      <div class="card-mentors col-md-4 d-flex flex-column">
        <% if current_user.student %>
          <% chatroom = Chatroom.find_by(student: current_user, mentor: mentorship.mentor) %>
          <p><%= mentorship.mentor.username.capitalize %></p>
          <% image_url =  mentorship.mentor.photo.attached? ? cl_image_path(mentorship.mentor.photo.key) : "https://www.promoview.com.br/uploads/images/unnamed%2819%29.png" %>
          <div class="user-img" style="background-image: url('<%= image_url %>');"></div>
          <%= link_to "Abrir chat", chatroom_path(chatroom), class: "btn-default-big" if mentorship.accepted %>
        </div>

        <% else %>
          <p><%= mentorship.student.username.capitalize %></p>
          <% image_url =  mentorship.student.photo.attached? ? cl_image_path(mentorship.student.photo.key) : "https://www.promoview.com.br/uploads/images/unnamed%2819%29.png" %>
          <div class="user-img" style="background-image: url('<%= image_url %>');"></div>

          <div class="butao">
            <%= link_to "Aceitar", mentorship_path(mentorship), data: { "turbo_method": :patch }, class: "btn-default-update" %>
            <%= link_to "Recusar", mentorship_path(mentorship), data: { "turbo_method": :delete, turbo_confirm: "Deseja realmente finalizar?" }, class: "btn-default-delete"  %>
          </div>
    </div>
      <% end %>
      <% end %>
  </div>


    <%= link_to "Voltar", profile_path, class: "btn-default btn-skills" %>

</div>

app/views/mentorships/new.html.erb
<h1> Ooioioi </h1>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
        <small>
          <strong><%= message.user.username %></strong>
          <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </small>
        <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="container-sm">
  <h1 class="logo-body">girls.match()</h1>
  <div class="row align-items-center">
      <div class="col-md-6">
        <div class="card-infos-home">
          <p style="text-align: justify;">
          <strong>O match certo pra uma carreira de sucesso!</strong> <br>
        Sabe aquela insegurança de se candidatar a uma vaga de emprego?
        É com o intuito de fortalecer a presença feminina nesses espaços que surgiu o girls.match().
        Aqui, mulheres de todas as senioridades dentro da área tech podem se encontrar para oferecer ou requerer mentoria. Buscamos motivar e promover oportunidades para que você possa dar os primeiros passos necessarios nessa área.
        Venha programar com a gente!
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <%= image_tag "pngaaa-com-2437155.png", class:"flower" %>
      </div>
    </div>
  </div>
  <div>
   <h2 class="h2-depositions">Depoimentos</h2>
  </div>
  <div class="depositions row">
    <div class="col-md-4">
        <p class="p-balloon">Encotrei a mentora <br>
                             certa e só tive sucesso.</p>
      <%= image_tag "pngwing-com.png", class:"balloon" %>
      <div class="cards-depositions">
        <%= image_tag "https://cdn.eutotal.com/imagens/mulheres-de-rosto-redondo.jpg", class:"card-picture" %>
      </div>
    </div>
    <div class="col-md-4">
        <p class="p-balloon">Agradeço o girlsmatch<br>
                             pela facilidade e sucesso</p>
      <%= image_tag "pngwing-com.png", class:"balloon" %>
      <div class="cards-depositions">
        <%= image_tag "https://ae01.alicdn.com/kf/H83932ab7323140418b80ce1b968fd1643/culos-de-prote-o-da-luz-azul-para-homem-e-mulher-arma-o-quadrada-de.jpg_Q90.jpg_.webp", class:"card-picture" %>
      </div>
    </div>
    <div class="col-md-4">
    <p class="p-balloon">Obrigado girlsmatch <br>
                         por mostrar que sou capaz</p>
      <%= image_tag "pngwing-com.png", class:"balloon" %>
      <div class="cards-depositions">
        <%= image_tag "https://www.metroworldnews.com.br/resizer/yTqU6THXHo97Z9l3rSLUN1xbMM4=/800x0/filters:format(jpg):quality(70):focal(329x433:339x443)/cloudfront-us-east-1.images.arcpublishing.com/metroworldnews/2NPZD6KZTZFRNOBNCQCVTYSO5U.jpg", class:"card-picture" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="footer-icons">
          <a href="https://github.com/tainanbogo"><i class="fab fa-github"></i></a>
          <a href="https://www.linkedin.com/in/tainanbogo/"><i class="fab fa-linkedin"></i></a>
          <p class="p-footer">Tainan Bogo</p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="footer-icons">
          <a href="https://github.com/annecaroline93"><i class="fab fa-github"></i></a>
          <a href="https://www.linkedin.com/in/anne-caroline-deegan/"><i class="fab fa-linkedin"></i></a>
          <p class="p-footer">Anne Deegan</p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="footer-icons">
          <a href="https://github.com/MarceloSFilho"><i class="fab fa-github"></i></a>
          <a href="https://www.linkedin.com/in/marcelomanoelf/"><i class="fab fa-linkedin"></i></a>
          <p class="p-footer">Marcelo Manoel</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
     <p>girls.match()</p>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://www.promoview.com.br/uploads/images/unnamed%2819%29.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Perfil", profile_path, class: "dropdown-item" %>
              <%= link_to "Editar Perfil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Junte-se a nós", new_user_registration_path , class: "nav-link" %>
          </li>
          <p class="vertical-bar">|</p>
          <li class="nav-item">
            <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/skills/_form.html.erb
 <%= simple_form_for(@skill) do |f| %>
  <%= f.input :language, collection: Skill::LANGUAGES, include_blank: false %>
  <%= f.button :submit, "Adicionar", class:"btn-default-update" %>
<% end %>

app/views/skills/new.html.erb
<div class="container">
  <h2 class="sign">Minhas habilidades</h2>

  <%= render "skills/form"  %>

  <div class="container container-skills">
    <ul class="skill-bold">
      <% current_user.skills.each do |skill| %>
              <li><%= skill.language %>
                  <%= button_to "Excluir skill", skill_path(skill), method: :delete, class: "btn-default-delete" %>
              </li>
      <% end %>
    </ul>

  </div>

  <%= link_to "Voltar", profile_path, class: "btn-default" %>

</div>

app/views/skills/update.html.erb
<h1>SET SKILLS</h1>

app/views/users/profile.html.erb
<h1>USER PAGE</h1>

 <%= link_to "Choose a mentor", mentorships_path, class:"btn btn-primary" %><br />
 <%= link_to "My proposals", my_proposals_path, class:"btn btn-primary" %><br />
 <%= link_to "My skills", new_skill_path, class:"btn btn-primary" %><br />
<% if @user.skills.present? %>
<ul>
<% @user.skills.each do |skill| %>
<li><%= skill.language %><%= button_to "delete skill", skill_path(skill), method: :delete, class: "btn-default-big" %></li>
<% end %>
</ul>
<% else %>
    <h2>You do not have any skills selected yet!</h2>
<% end %>
<div class="container text-center">
  <div class="row">
    <div class="card-view col-md-6">
      <% image_url =  current_user.photo.attached? ? cl_image_path(current_user.photo.key) : "https://www.promoview.com.br/uploads/images/unnamed%2819%29.png" %>
        <div class="user-img" style="background-image: url('<%= image_url %>');"></div>
      <div class="skill-info card-infos">
          <% if @user.skills.present? %>
            <ul class="ul-style">
            <% @user.skills.each do |skill| %>
            <li><%= skill.language %></li> <br>
            <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    <div class="col-md-6">
      <h2 class="h2-mt">Instruções</h2>
      <% if current_user.mentor? %>
        <p class="p-bold">
          MENTORA:
        </p>

        <p class="ta-center">

          Olá! É muito bom te ver por aqui! Lembra daquele frio na barriga que todos nós temos quando iniciamos uma carreira? Pois é, aqui estamos rodeadas de mulheres passando por este processo! Vamos contribuir para que Desenvolvedoras Junior dêem os melhores passos em direção a uma carreira de sucesso! Não se esqueça: paciência e empatia são primordiais neste processo, por isso seja gentil com as inseguranças da sua mentorada. Lembre-se, você só pode aceitar um convite por vez, e só ficará disponivel novamente assim que a mentoria for completada. Vamos construir uma comunidade de mulheres na tecnologia!</p>
        </p>
      <% end %>
      <% if current_user.student? %>
        <p class="p-bold">
          ESTUDANTE:
        </p>
        <p class="ta-center">

          Bem vinda! É muito bom te ver por aqui! Queremos que você tenha a melhor experiência possível e alcançe seus objetivos com clareza e assertividade. Para isso, você pode escolher uma mentora através da lista disponível. Você pode enviar apenas um convite por mentora, caso ela aceite ambas só estarão disponíveis para novas mentorias após esta ser completada. Boa jornada! Vamos construir uma comunidade de mulheres na tecnologia!
        </p>
      <% end %>

      </div>
    </div>

  <div class="row">
    <div class="col">
        <%= link_to "Convites", my_proposals_path, class:"btn-instructions btn-default-big" %>
    </div>
    <div class="col">
        <% if current_user.student? %>
          <%= link_to "Encontre uma mentora", mentorships_path, class:"btn-instructions btn-default-big" %>
        <% end %>
        <% if current_user.mentor? %>
          <%= link_to "Habilidades", new_skill_path, class:"btn-instructions btn-default-big" %>
        <% end %>
    </div>
  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h2 class="sign"><%= @user.username.capitalize %></h2>
      <div class="description-card">
        <%= @user.description %>
      </div>
    </div>
    <div class="card-view col-6">
      <div class="card-img">
          <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "card-picture" %>
          <% else %>
          <%= image_tag "https://www.promoview.com.br/uploads/images/unnamed%2819%29.png", class: "card-picture" %>
          <% end %>
      </div>
      <div class=" card-infos">
          <% if @user.skills.present? %>
            <ul class="ul-style">
            <% @user.skills.each do |skill| %>
            <li><%= skill.language %></li>
            <% end %>
            </ul>
          <% end %>
      </div>
    </div>
    <div>
    <%= link_to "Voltar", mentorships_path, class: "btn-default" %>
    <%= link_to "Enviar convite", user_mentorships_path(@user), data: { "turbo_method": :post }, class:"btn-default-big" %>
    </div>
  </div>
</div>